name: Build, Test and Push

on:
  push:
    branches: [ '**' ]

env:
  IMAGE_NAME: helloworld

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #----------------------------------

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.EOF_REGISTRY }}
      #     username: ${{ secrets.EOF_REGISTRY_USERNAME }}
      #     password: ${{ secrets.EOF_REGISTRY_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ github.sha }}
      #     labels: ${{ steps.meta.outputs.labels }}

      #------------  OR  ---------------

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.EOF_REGISTRY_USERNAME }}
          aws-secret-access-key: ${{ secrets.EOF_REGISTRY_TOKEN }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Tag, and push image to Amazon ECR
        env:
          RELEASE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ secrets.EOF_REGISTRY }}/${{ env.IMAGE_NAME }}:$RELEASE_TAG .
          docker push ${{ secrets.EOF_REGISTRY }}/${{ env.IMAGE_NAME }}:$RELEASE_TAG

      #----------------------------------

      - name: Transistor
        uses: 'Even-on-Fridays/transistor-register-artifact-action@main'
        with:
          docker-image: ${{ secrets.EOF_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          org-id: ${{ secrets.EOF_SUITE_ORG_ID }}